OPCODE_DISPATCH = 0
OPCODE_HEARTBEAT = 1
OPCODE_IDENTIFY = 2
OPCODE_STATUS_UPDATE = 3
OPCODE_VOICE_STATE_UPDATE = 4
OPCODE_VOICE_SERVER_PING = 5
OPCODE_RESUME = 6
OPCODE_RECONNECT = 7
OPCODE_REQUEST_GULID_MEMBERS = 8
OPCODE_INVALID_SESSION = 9
OPCODE_HELLO = 10
OPCODE_HEARTBEAT_ACK = 11

STATUS_ONLINE = "online"
STATUS_DO_NOT_DISTURB = "dnd"
STATUS_IDLE = "idle"
STATUS_INVISIBLE = "invisible"
STATUS_OFFLINE = "offline"

GAME_TYPE_PLAYING = 0
GAME_TYPE_STREAMING = 1
GAME_TYPE_LISTENING = 2
GAME_TYPE_WATCHING = 3
